DROP TABLE IF EXISTS `wine_detail`;
CREATE TABLE `wine_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `brand_id` int(11) NOT NULL COMMENT '品牌id',
  `name` varchar(200) NOT NULL COMMENT '商品名',
  `price` varchar(20) NOT NULL COMMENT '商品价格',
  `name_jiuxian` varchar(200) NOT NULL COMMENT '酒仙网商品名',
  `price_jiuxian` varchar(20) NOT NULL COMMENT '价格',
  `origin` varchar(50) NOT NULL COMMENT '产地',
  `company` varchar(50) NOT NULL COMMENT '酒厂',
  `content` varchar(20) NOT NULL COMMENT '净含量',
  `alcohol` varchar(20) NOT NULL COMMENT '酒精度',
  `specifications` varchar(20) NOT NULL COMMENT '规格',
  `conditions` varchar(50) NOT NULL COMMENT '储藏条件',
  `xianggui` varchar(20) NOT NULL COMMENT '箱规',
  `material` varchar(50) NOT NULL COMMENT '原料',
  `scent` varchar(50) NOT NULL COMMENT '香型',
  `score_jiuxian` varchar(20) NOT NULL COMMENT '评分',
  `change_time` int(11) NOT NULL COMMENT '时间戳',
  `createtime` datetime NOT NULL COMMENT '创建时间',
  `id_jiuxian` varchar(50) NOT NULL,
  `wine_type` varchar(50) NOT NULL COMMENT '产品类型',
  `chanqu` varchar(50) NOT NULL COMMENT '产区',
  `name_1919` varchar(200) NOT NULL COMMENT '1919商品名',
  `score_1919` varchar(20) NOT NULL COMMENT '1919_评分',
  `price_1919` varchar(20) NOT NULL COMMENT '1919价格',
  `id_1919` varchar(50) NOT NULL,
  `name_jd` varchar(200) NOT NULL COMMENT '京东酒名',
  `goodRate_jd` varchar(20) NOT NULL COMMENT '京东好评率',
  `generalRate_jd` varchar(20) NOT NULL COMMENT '京东中评率',
  `poorRate_jd` varchar(20) NOT NULL COMMENT '京东中评',
  `price_jd` varchar(20) NOT NULL COMMENT '京东价',
  `id_jd` varchar(100) NOT NULL COMMENT '京东唯一标识',
  `pic_jiuxian` text NOT NULL COMMENT '图集',
  `pic_1919` text NOT NULL,
  `pic_jd` text NOT NULL,
  `status` tinyint(4) NOT NULL DEFAULT '1',
  `bigpic_jiuxian` text NOT NULL,
  `bigpic_1919` text NOT NULL,
  `bigpic_jd` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;